core/urls.py
from django.urls import path

from .views import index


app_name = 'core'


urlpatterns = [
    path('', index, name='index'),
]

link/urls.py
from django.urls import path

from .views import add_link, add_review, detail


app_name = 'link'


urlpatterns = [
    path('add/', add_link, name='add_link'),
    path('<int:pk>/', detail, name='detail'),
    path('<int:pk>/add/', add_review, name='add_review'),
]

linkrater/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('links/', include('link.urls')),
    path('', include('core.urls')),
    path('', include('user.urls')),
]

user/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from .views import signup


app_name = 'user'


urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', LoginView.as_view(template_name='user/login.html'), name='login'),
]

core/models.py
from django.db import models

# Create your models here.

link/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class Link(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name
    
    def get_rating(self):
        if self.reviews.count():
            total_score = 0

            for review in self.reviews.all():
                total_score += review.rating

            return total_score / self.reviews.count()
        
        return 'No reviews'
    

class Review(models.Model):
    link = models.ForeignKey(Link, related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='reviews', on_delete=models.CASCADE)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.link.name} - {self.rating} stars by {self.user.username}'

user/models.py
from django.db import models

# Create your models here.

link/forms.py
from django import forms

from .models import Link, Review


class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ('name', 'url',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'w-full mt-2 py-4 px-6 bg-slate-100 border border-slate-300'}),
            'url': forms.URLInput(attrs={'class': 'w-full mt-2 py-4 px-6 bg-slate-100 border border-slate-300'})
        }


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('rating', 'content',)
        widgets = {
            'rating': forms.NumberInput(attrs={'class': 'w-full mt-2 py-4 px-6 bg-slate-100 border border-slate-300'}),
            'content': forms.Textarea(attrs={'class': 'w-full mt-2 py-4 px-6 bg-slate-100 border border-slate-300'})
        }

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)
    
    def save(self, commit=True):
        user = super(CustomUserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        
        return user

core/views.py
from django.shortcuts import render

from link.models import Link


def index(request):
    links = Link.objects.all()

    return render(request, 'core/index.html', {
        'links': links
    })

link/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import LinkForm, ReviewForm
from .models import Link


def detail(request, pk):
    link = get_object_or_404(Link, pk=pk)

    return render(request, 'link/detail.html', {
        'link': link
    })


@login_required
def add_link(request):
    if request.method == 'POST':
        form = LinkForm(request.POST)

        if form.is_valid():
            link = form.save()

            return redirect('link:detail', pk=link.pk)
    else:
        form = LinkForm()
    
    return render(request, 'link/add_link.html', {
        'form': form
    })


@login_required
def add_review(request, pk):
    link = get_object_or_404(Link, pk=pk)

    if request.method == 'POST':
        form = ReviewForm(request.POST)

        if form.is_valid():
            review = form.save(commit=False)
            review.link = link
            review.user = request.user
            review.save()

            return redirect('link:detail', pk=pk)
    else:
        form = ReviewForm()
    
    return render(request, 'link/add_review.html', {
        'form': form
    })

user/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import redirect, render

from .forms import CustomUserCreationForm


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            username = form.cleaned_data.get('username')
            password1 = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password1)

            login(request, user)

            return redirect('/')
    else:
        form = CustomUserCreationForm()
    
    return render(request, 'user/signup.html', {
        'form': form
    })

core/templates/core/base.html
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>LinkRater | {% block title %}{% endblock %}</title>
    </head>

    <body>
        <nav class="py-6 px-12 flex items-center justify-between bg-purple-700">
            <a href="{% url 'core:index' %}" class="text-2xl text-white font-bold">LinkRater</a>

            <div class="space-x-6">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'link:add_link' %}" class="py-4 px-8 bg-purple-900 text-white">Add link</a>
                {% else %}
                    <a href="{% url 'user:login' %}" class="py-4 px-8 bg-purple-900 text-white">Log in</a>

                    <a href="{% url 'user:signup' %}" class="py-4 px-8 bg-purple-500 text-white">Sign up</a>
                {% endif %}
            </div>
        </nav>

        <main class="py-6 px-12">
            {% block content %}
            {% endblock %}
        </main>

        <script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="4bb38989-54e1-426d-8b68-cb0ec8d17514"  type="text/javascript"></script>
    </body>
</html>

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="grid grid-cols-10">
        <div class="col-span-3 py-6 px-8 font-bold bg-purple-700 text-white">Name</div>
        <div class="col-span-6 py-6 px-8 font-bold bg-purple-700 text-white">Url</div>
        <div class="col-span-1 py-6 px-8 font-bold bg-purple-700 text-white">Rating</div>
    </div>

    {% for link in links %}
        <div class="grid grid-cols-10">
            <div class="col-span-3 py-3 px-8">
                <a href="{% url 'link:detail' link.pk %}">{{ link.name }}</a>
            </div>
            <div class="col-span-6 py-3 px-8">{{ link.url }}</div>
            <div class="col-span-1 py-3 px-8">{{ link.get_rating }}</div>
        </div>
    {% endfor %}
{% endblock %}

link/templates/link/add_link.html
{% extends 'core/base.html' %}

{% block title %}Add link{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl text-purple-800 font-bold">Add link</h1>

    <form method="post" action="." class="space-y-4">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="py-4 px-8 bg-purple-700 text-white">Submit</button>
    </form>
{% endblock %}

link/templates/link/add_review.html
{% extends 'core/base.html' %}

{% block title %}Add review{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl text-purple-800 font-bold">Add review</h1>

    <form method="post" action="." class="space-y-4">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="py-4 px-8 bg-purple-700 text-white">Submit</button>
    </form>
{% endblock %}

link/templates/link/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ link.name }}{% endblock %}

{% block content %}
    <h1 class="mb-6 text-3xl text-purple-800 font-bold">{{ link.name }}</h1>

    <p class="text-slate-600"><span class="font-bold">Url:</span> {{ link.url }}</p>
    <p class="text-slate-600"><span class="font-bold">Rating:</span> {{ link.get_rating }}</p>

    <a href="{% url 'link:add_review' link.pk %}" class="mt-6 py-4 px-8 inline-block bg-purple-900 text-white">Add review</a>

    <hr class="my-6">

    <h2 class="mb-6 text-xl font-bold text-purple-800">Reviews</h2>

    {% for review in link.reviews.all %}
        <div class="mb-4 py-4 px-6 bg-purple-100">
            <h3 class="text-xl font-bold text-purple-800">{{ review.user.username }}</h3>

            <p class="text-xs"><span class="font-bold">Rating:</span> {{ review.rating }}</p>

            <p class="mt-6">
                {{ review.content }}
            </p>
        </div>
    {% endfor %}
{% endblock %}

user/templates/user/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
    <h1 class="text-3xl text-purple-800 font-bold">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="py-4 px-8 bg-purple-700 text-white">Submit</button>
    </form>
{% endblock %}

user/templates/user/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <h1 class="text-3xl text-purple-800 font-bold">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="py-4 px-8 bg-purple-700 text-white">Submit</button>
    </form>
{% endblock %}